name = "Wold's Vaults"
author = "iwolfking"
version = "0.34.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6e643ab1b3a27b183bde97636d0b38a93ca532197156c3443157b9dd2f1bd8a"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
