name = "Wold's Vaults"
author = "iwolfking"
version = "0.34.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6894fd11652deddb8f86fd4bbc99b85c1dc85eb2845585ac272c9b4c57f974c"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
