name = "Wold's Vaults"
author = "iwolfking"
version = "0.34.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc8e9e9a0d293ae9bcece4b90c9474fe763eedc486aded113bf04babdebaf618"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
